## Basic Into to K-Nearest Neighbors Algorithm in Scikit Learn

In [1]:
from sklearn.neighbors import NearestNeighbors
import numpy as np

### First example is for a 2D set of points and a search of 3 closest neighbors to a single search point 

In [2]:
data = np.array([[-1, -1], [-2, -1], [1,1], [-3, -2], [2, 1], [3, 2]])
new_pont1 = np.array([-1,-1])
new_pont1 = new_pont1.reshape(1,-1)
n_neighbors = 3
nbrs = NearestNeighbors(n_neighbors=n_neighbors, algorithm='ball_tree').fit(data)
dist, ind = nbrs.kneighbors(new_pont1)
print("Distance is: {}".format(dist))
print("Indices of closest points are: {}".format(ind))
graph = nbrs.kneighbors_graph(new_pont1).toarray()
print(" A sparse graph showing the connections between neighboring points is shown here: {}".format(graph))

Distance is: [[ 0.          1.          2.23606798]]
Indices of closest points are: [[0 1 3]]
 A sparse graph showing the connections between neighboring points is shown here: [[ 1.  1.  0.  1.  0.  0.]]


### Next example is for a 2D set of points and serch of 3 closest neighbors to 2 pair of search points

In [3]:
new_pont2 = np.array([[-1,-1], [1, 1]])
dist, ind = nbrs.kneighbors(new_pont2)
print("Distance is: \n{}".format(dist))
print("Indices of closest points are: \n{}".format(ind))
graph = nbrs.kneighbors_graph(new_pont2).toarray()
print(" A sparse graph showing the connections between neighboring points is shown here: \n{}".format(graph))

Distance is: 
[[ 0.          1.          2.23606798]
 [ 0.          1.          2.23606798]]
Indices of closest points are: 
[[0 1 3]
 [2 4 5]]
 A sparse graph showing the connections between neighboring points is shown here: 
[[ 1.  1.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  1.  1.]]
